title: Create Raspberry Pi Virtual Machine
hero_image: images/banner.PNG
description: Create a Raspberry Pi Desktop Virtual Machine using VirtualBox.
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Download Raspberry Pi Desktop
- title: Install Oracle VM VirtualBox
- title: Create a new Virtual Machine (VM)
- title: Install Raspberry Pi Desktop
- title: Raspberry Pi Deskop Setup
- title: Using your Virtual Machine